name: hp-suite
on: [push, pull_request, workflow_dispatch]
jobs:
  run-hp-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy matplotlib plotly pyyaml
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
      - name: Build impacts PDF + Robin slide
        run: |
          make hr-ia-impacts
          make robin-slide
      - name: HP tests (local suite)
        run: make hp-test-all || true
      - name: Gates by branch
        run: |
          BR="${{ github.ref_name }}"
          if [ "$BR" = "main" ]; then
            make hp-ci-gates-prod || true
          elif [ "$BR" = "staging" ]; then
            make hp-ci-gates-staging || true
          else
            make hp-ci-gates-dev || true
          fi
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: interia-artefacts
          path: |
            docs/impacts_IA_HR.pdf
            slides/robin_interia_beamer.pdf
